default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hubbubb
  password: Tootb1217

development:
  <<: *default
  database: hubbubb_development

test:
  <<: *default
  database: hubbubb_test

production:
  <<: *default
  database: hubbubb_production
  username: hubbubb
  password: <%= ENV['HUBBUBB_DATABASE_PASSWORD'] %>
